main {
  read_symbol {
    bbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbb
    while
      ggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeee
      dddddaccccbbbfffffffa
    do eeeeeeeeeeeedddddfffffffa
      bbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffadddddbbbggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbb
      fffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffa
    done fffffffa
    eeeeeedddddfffffffaeeeeeedddddbbbbbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffafffffff
  }
  read_symbol {
    bbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbb
    while
      ggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeee
      dddddaccccbbbfffffffa
    do eeeeeeeeeeeedddddfffffffa
      bbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffadddddbbbggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbb
      fffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffa
    done fffffffa
    eeeeeedddddfffffffaeeeeeedddddbbbbbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffafffffff
  }
  read_symbol {
    bbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbb
    while
      ggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeee
      dddddaccccbbbfffffffa
    do eeeeeeeeeeeedddddfffffffa
      bbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffadddddbbbggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbb
      fffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffa
    done fffffffa
    eeeeeedddddfffffffaeeeeeedddddbbbbbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffafffffff
  }
  read_symbol {
    bbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbb
    while
      ggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeee
      dddddaccccbbbfffffffa
    do eeeeeeeeeeeedddddfffffffa
      bbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffadddddbbbggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbb
      fffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffa
    done fffffffa
    eeeeeedddddfffffffaeeeeeedddddbbbbbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffafffffff
  }
  read_symbol {
    bbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbb
    while
      ggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeee
      dddddaccccbbbfffffffa
    do eeeeeeeeeeeedddddfffffffa
      bbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffadddddbbbggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbb
      fffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffa
    done fffffffa
    eeeeeedddddfffffffaeeeeeedddddbbbbbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffafffffff
  }
  read_symbol {
    bbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbb
    while
      ggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeee
      dddddaccccbbbfffffffa
    do eeeeeeeeeeeedddddfffffffa
      bbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffadddddbbbggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbb
      fffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffa
    done fffffffa
    eeeeeedddddfffffffaeeeeeedddddbbbbbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffafffffff
  }
  read_symbol {
    bbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbb
    while
      ggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeee
      dddddaccccbbbfffffffa
    do eeeeeeeeeeeedddddfffffffa
      bbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffadddddbbbggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbb
      fffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffa
    done fffffffa
    eeeeeedddddfffffffaeeeeeedddddbbbbbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffafffffff
  }
  read_symbol {
    bbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbb
    while
      ggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeee
      dddddaccccbbbfffffffa
    do eeeeeeeeeeeedddddfffffffa
      bbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffadddddbbbggggggggeeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbb
      fffffffabbbeeeeeedddddfffffffccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffa
    done fffffffa
    eeeeeedddddfffffffaeeeeeedddddbbbbbbeeeeeedddddfffffffcccceeeeeedddddaeeeeeedddddbbbbbbccccaafffffffaeeeeeedddddbbbccccafffffffbbbbbbbbbeeeeeedddddaaaccccbbbbbbbbbfffffffafffffffafffffff
  }
  bbbggggggggeeeeee
  if
    eeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeee
    dddddffffffffffffffccccbbbeeeeeedddddadddddbbbfffffffa
  then eeeeeeeeeeeedddddfffffffa
    eeeeeedddddfffffffa
    print_symbol(s=8) {
      eeeeeedddddfffffffcccccccccccccccccccccccccccccccceeeeeedddddeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddfffffffaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaaafffffffbbbeeeeeehhhhhhhhhbbbfffffffaeeeeeeafffffffeeeeeedddddfffffffcccccccccccccccccccccccccccccccceeeeeedddddeeeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaadddddfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
    }
    bbb
  end bbbeeeeeedddddffffffffffffffa
  if
    eeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbcccc
    aeeeeeedddddffffffffffffffccccbbbeeeeeedddddadddddbbbfffffffa
  then eeeeeeeeeeeedddddfffffffa
    eeeeeedddddfffffffa
    print_symbol(s=7) {
      eeeeeedddddfffffffcccccccccccccccccccccccccccceeeeeedddddeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddfffffffaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaafffffffbbbeeeeeehhhhhhhhhbbbfffffffaeeeeeeafffffffeeeeeedddddfffffffcccccccccccccccccccccccccccceeeeeedddddeeeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccc
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaadddddfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
    }
    bbb
  end bbbeeeeeedddddffffffffffffffa
  if
    eeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffccccbbbeeeeeedddddadddddbbbfffffffa
  then eeeeeeeeeeeedddddfffffffa
    eeeeeedddddfffffffa
    print_symbol(s=6) {
      eeeeeedddddfffffffcccccccccccccccccccccccceeeeeedddddeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddfffffffaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaafffffffbbbeeeeeehhhhhhhhhbbbfffffffaeeeeeeafffffffeeeeeedddddfffffffcccccccccccccccccccccccceeeeeedddddeeeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaaaadddddfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
    }
    bbb
  end bbbeeeeeedddddffffffffffffffa
  if
    eeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffccccbbbeeeeeedddddadddddbbbfffffffa
  then eeeeeeeeeeeedddddfffffffa
    eeeeeedddddfffffffa
    print_symbol(s=5) {
      eeeeeedddddfffffffcccccccccccccccccccceeeeeedddddeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddfffffffaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaafffffffbbbeeeeeehhhhhhhhhbbbfffffffaeeeeeeafffffffeeeeeedddddfffffffcccccccccccccccccccceeeeeedddddeeeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaadddddfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
    }
    bbb
  end bbbeeeeeedddddffffffffffffffa
  if
    eeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbddddd
    afffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffccccbbbeeeeeedddddadddddbbbfffffffa
  then eeeeeeeeeeeedddddfffffffa
    eeeeeedddddfffffffa
    print_symbol(s=4) {
      eeeeeedddddfffffffcccccccccccccccceeeeeedddddeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddfffffffaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaafffffffbbbeeeeeehhhhhhhhhbbbfffffffaeeeeeeafffffffeeeeeedddddfffffffcccccccccccccccceeeeeedddddeeeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaadddddfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
    }
    bbb
  end bbbeeeeeedddddffffffffffffffa
  if
    eeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaeeeeeeddddd
    bbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffccccbbbeeeeeedddddadddddbbbfffffffa
  then eeeeeeeeeeeedddddfffffffa
    eeeeeedddddfffffffa
    print_symbol(s=3) {
      eeeeeedddddfffffffcccccccccccceeeeeedddddeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddfffffffaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaafffffffbbbeeeeeehhhhhhhhhbbbfffffffaeeeeeeafffffffeeeeeedddddfffffffcccccccccccceeeeeedddddeeeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaadddddfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
    }
    bbb
  end bbbeeeeeedddddffffffffffffffa
  if
    eeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffccccbbbeeeeeedddddadddddbbbfffffffa
  then eeeeeeeeeeeedddddfffffffa
    eeeeeedddddfffffffa
    print_symbol(s=2) {
      eeeeeedddddfffffffcccccccceeeeeedddddeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddfffffffaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaafffffffbbbeeeeeehhhhhhhhhbbbfffffffaeeeeeeafffffffeeeeeedddddfffffffcccccccceeeeeedddddeeeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccaaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaadddddfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
    }
    bbb
  end bbbeeeeeedddddffffffffffffffa
  if
    eeeeeedddddbbbccccbbbccccaafffffffbbbbbbeeeeeedddddaaccccbbbbbbfffffffabbbeeeeeedddddfffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccaeeeeeedddddbbbdddddafffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffbbbeeeeeedddddaccccbbbfffffffaeeeeeebbbccccaeeeeeedddddffffffffffffffccccbbbeeeeeedddddadddddbbbfffffffa
  then eeeeeeeeeeeedddddfffffffa
    eeeeeedddddfffffffa
    print_symbol(s=1) {
      eeeeeedddddfffffffcccceeeeeedddddeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddfffffffaaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaaaafffffffbbbeeeeeehhhhhhhhhbbbfffffffaeeeeeeafffffffeeeeeedddddfffffffcccceeeeeedddddeeeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccaaaaaaaaaaaa
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      aaaaaaaadddddfffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffff
    }
    bbb
  end bbbeeeeeedddddffffffffffffffa
  eeeeeehhhhhhhhheeeeeedddddffffffffffffffeeeeeedddddfffffffabbbggggggggfffffff
}
