#! /usr/bin/env bash

set -e

day="$1"; shift

if test -n "$GHCOPTS"; then
   opts="--ghc-options $GHCOPTS"
fi

stack build $opts aoc2019:$day
ulimit -v 7000000 -m 7000000
stack exec $day -- ../input "$@"
