# stylish-haskell configuration file
# ==================================

steps:
  - module_header:
      indent: 2
      sort: false
      separate_lists: true
      break_where: single
      open_bracket: next_line

  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
      multi_way_if: always

  - imports:
      align: global
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 2
      separate_lists: true
      space_surround: false
      post_qualify: true
      group_imports: false

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
      language_prefix: LANGUAGE

  - trailing_whitespace: {}

newline: lf
cabal: true
