name: aoc

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wredundant-constraints
  - -fwarn-tabs

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PackageImports
  - RankNTypes
  - RecordWildCards
  - RoleAnnotations
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - QuickCheck
  - array
  - base16-bytestring
  - bytestring
  - containers
  - cryptohash-md5
  - data-has
  - extra
  - filepath
  - hashable
  - insert-ordered-containers
  - lens
  - monad-loops
  - monad-st
  - mtl
  - parallel
  - parsec
  - pqueue
  - primitive
  - random
  - safe
  - split
  - strict
  - string-qq
  - tardis
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - text
  - time
  - transformers-base
  - transformers
  - unordered-containers
  - vector

library:
  source-dirs: lib

_exe: &exe
  ghc-options:
    - -O2
    - -threaded -rtsopts -with-rtsopts=-N4
    - -fno-warn-missing-signatures
    - -fno-warn-unused-top-binds
    - -fno-warn-unused-do-bind
  dependencies: aoc

executables:
  aoc: {
    <<: *exe,
    source-dirs: src,
    default-extensions: [NoImplicitPrelude],
    main: Main.hs
  }

  # animation_test: {
  #   <<: *exe,
  #   other-modules: [],
  #   main: app/AnimationTest.hs
  # }
  #
  # pf_test: {
  #   <<: *exe,
  #   other-modules: [],
  #   main: app/PathFindingTest.hs
  # }
